sudo: false
language: php

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - vendor

before_script:
  - travis_retry composer install --no-interaction
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit
